MERGE INTO PRINCIPLE_GROUP values (1, 'ROLE_ADMINISTRATOR');
MERGE INTO PRINCIPLE_GROUP values (2, 'ROLE_USER');
MERGE INTO PRINCIPLE_GROUP values (3, 'ROLE_ACCOUNTANT');
MERGE INTO PRINCIPLE_GROUP values (4, 'ROLE_AUDITOR');